<?php

declare(strict_types=1);

namespace App\Enums;

enum JenisNotifikasi: string
{
    case BOOKING_DISETUJUI = 'BOOKING_DISETUJUI';
    case BOOKING_DITOLAK = 'BOOKING_DITOLAK';
    case JAM_GROOMING_DIUPDATE = 'JAM_GROOMING_DIUPDATE';
    case REMINDER_PEMBAYARAN = 'REMINDER_PEMBAYARAN';
    case PEMBAYARAN_JATUH_TEMPO = 'PEMBAYARAN_JATUH_TEMPO';
    case MONITORING_PENITIPAN = 'MONITORING_PENITIPAN';
    case LAYANAN_SELESAI = 'LAYANAN_SELESAI';
    case BOOKING_DIBATALKAN = 'BOOKING_DIBATALKAN';
    case STATUS_REFUND = 'STATUS_REFUND';
    case PERPANJANGAN_PENITIPAN_MENUNGGU_KONFIRMASI = 'PERPANJANGAN_PENITIPAN_MENUNGGU_KONFIRMASI';
    case PERPANJANGAN_PENITIPAN_DISETUJUI = 'PERPANJANGAN_PENITIPAN_DISETUJUI';
    case PERPANJANGAN_PENITIPAN_DITOLAK = 'PERPANJANGAN_PENITIPAN_DITOLAK';
    case PERPANJANGAN_PENITIPAN_MENUNGGU_PEMBAYARAN = 'PERPANJANGAN_PENITIPAN_MENUNGGU_PEMBAYARAN';
}
