<?php

declare(strict_types=1);

use App\Controllers\Admin\NotifikasiController as AdminNotifikasiController;
use App\Controllers\Admin\DashboardController as AdminDashboardController;
use App\Controllers\Admin\GroomingController as AdminGroomingController;
use App\Controllers\Admin\LaporanController as AdminLaporanController;
use App\Controllers\Admin\PenitipanController as AdminPenitipanController;
use App\Controllers\Admin\PengaturanController as AdminPengaturanController;
use App\Controllers\Admin\PetCareController as AdminPetCareController;
use App\Controllers\Admin\StaffManagementController as AdminStaffManagementController;
use App\Controllers\Admin\TransaksiController as AdminTransaksiController;
use App\Controllers\Auth\StaffAuthController;
use App\Core\Router;

/** @var Router $router */

$router->get('/admin/login', [StaffAuthController::class, 'showLogin'], ['guest']);
$router->post('/admin/login', [StaffAuthController::class, 'login'], ['guest']);
$router->post('/admin/logout', [StaffAuthController::class, 'logout'], ['auth:staff']);
$router->get('/admin/forgot-password', [StaffAuthController::class, 'showForgotPassword'], ['guest']);
$router->post('/admin/forgot-password', [StaffAuthController::class, 'forgotPassword'], ['guest']);
$router->get('/admin/reset-password', [StaffAuthController::class, 'showResetPassword'], ['guest']);
$router->post('/admin/reset-password', [StaffAuthController::class, 'resetPassword'], ['guest']);
$router->get('/admin/change-password', [StaffAuthController::class, 'showChangePassword'], ['auth:staff']);
$router->post('/admin/change-password', [StaffAuthController::class, 'changePassword'], ['auth:staff']);
$router->get('/admin/dashboard', [AdminDashboardController::class, 'index'], ['auth:staff']);
$router->get('/admin/notifikasi', [AdminNotifikasiController::class, 'index'], ['auth:staff']);
$router->get('/admin/staff', [AdminStaffManagementController::class, 'index'], ['auth:staff', 'role:owner']);
$router->get('/admin/staff/tambah', [AdminStaffManagementController::class, 'create'], ['auth:staff', 'role:owner']);
$router->post('/admin/staff/tambah', [AdminStaffManagementController::class, 'store'], ['auth:staff', 'role:owner']);
$router->get('/admin/staff/edit', [AdminStaffManagementController::class, 'edit'], ['auth:staff', 'role:owner']);
$router->post('/admin/staff/edit', [AdminStaffManagementController::class, 'update'], ['auth:staff', 'role:owner']);
$router->get('/admin/staff/reset-password', [AdminStaffManagementController::class, 'resetPasswordForm'], ['auth:staff', 'role:owner']);
$router->post('/admin/staff/reset-password', [AdminStaffManagementController::class, 'resetPassword'], ['auth:staff', 'role:owner']);
$router->post('/admin/staff/status', [AdminStaffManagementController::class, 'toggleStatus'], ['auth:staff', 'role:owner']);
$router->get('/admin/laporan', [AdminLaporanController::class, 'index'], ['auth:staff']);
$router->get('/admin/laporan/grooming', [AdminLaporanController::class, 'grooming'], ['auth:staff']);
$router->get('/admin/laporan/penitipan', [AdminLaporanController::class, 'penitipan'], ['auth:staff']);
$router->get('/admin/laporan/pet-care', [AdminLaporanController::class, 'petCare'], ['auth:staff']);
$router->get('/admin/transaksi', [AdminTransaksiController::class, 'index'], ['auth:staff']);
$router->get('/admin/pengaturan', [AdminPengaturanController::class, 'index'], ['auth:staff', 'role:owner']);
$router->post('/admin/pengaturan', [AdminPengaturanController::class, 'update'], ['auth:staff', 'role:owner']);
$router->get('/admin/pet-care/layanan', [AdminPetCareController::class, 'layananIndex'], ['auth:staff']);
$router->get('/admin/pet-care/layanan/tambah', [AdminPetCareController::class, 'layananCreate'], ['auth:staff']);
$router->post('/admin/pet-care/layanan/tambah', [AdminPetCareController::class, 'layananStore'], ['auth:staff']);
$router->get('/admin/pet-care/layanan/edit', [AdminPetCareController::class, 'layananEdit'], ['auth:staff']);
$router->post('/admin/pet-care/layanan/edit', [AdminPetCareController::class, 'layananUpdate'], ['auth:staff']);
$router->post('/admin/pet-care/layanan/hapus', [AdminPetCareController::class, 'layananDestroy'], ['auth:staff']);
$router->get('/admin/pet-care/slot', [AdminPetCareController::class, 'slotIndex'], ['auth:staff']);
$router->get('/admin/pet-care/slot/tambah', [AdminPetCareController::class, 'slotCreate'], ['auth:staff']);
$router->post('/admin/pet-care/slot/tambah', [AdminPetCareController::class, 'slotStore'], ['auth:staff']);
$router->post('/admin/pet-care/slot/tutup', [AdminPetCareController::class, 'slotClose'], ['auth:staff']);
$router->post('/admin/pet-care/slot/buka', [AdminPetCareController::class, 'slotOpen'], ['auth:staff']);
$router->post('/admin/pet-care/slot/hapus', [AdminPetCareController::class, 'slotDestroy'], ['auth:staff']);
$router->get('/admin/pet-care/booking', [AdminPetCareController::class, 'bookingIndex'], ['auth:staff']);
$router->post('/admin/pet-care/booking/status', [AdminPetCareController::class, 'bookingUpdateStatus'], ['auth:staff']);
$router->post('/admin/pet-care/booking/batalkan', [AdminPetCareController::class, 'bookingCancel'], ['auth:staff']);
$router->get('/admin/grooming/layanan', [AdminGroomingController::class, 'layananIndex'], ['auth:staff']);
$router->get('/admin/grooming/layanan/tambah', [AdminGroomingController::class, 'layananCreate'], ['auth:staff']);
$router->post('/admin/grooming/layanan/tambah', [AdminGroomingController::class, 'layananStore'], ['auth:staff']);
$router->get('/admin/grooming/layanan/edit', [AdminGroomingController::class, 'layananEdit'], ['auth:staff']);
$router->post('/admin/grooming/layanan/edit', [AdminGroomingController::class, 'layananUpdate'], ['auth:staff']);
$router->post('/admin/grooming/layanan/hapus', [AdminGroomingController::class, 'layananDestroy'], ['auth:staff']);
$router->get('/admin/grooming/kuota', [AdminGroomingController::class, 'kuotaIndex'], ['auth:staff']);
$router->get('/admin/grooming/kuota/tambah', [AdminGroomingController::class, 'kuotaCreate'], ['auth:staff']);
$router->post('/admin/grooming/kuota/tambah', [AdminGroomingController::class, 'kuotaStore'], ['auth:staff']);
$router->get('/admin/grooming/kuota/edit', [AdminGroomingController::class, 'kuotaEdit'], ['auth:staff']);
$router->post('/admin/grooming/kuota/edit', [AdminGroomingController::class, 'kuotaUpdate'], ['auth:staff']);
$router->post('/admin/grooming/kuota/hapus', [AdminGroomingController::class, 'kuotaDestroy'], ['auth:staff']);
$router->get('/admin/grooming/booking', [AdminGroomingController::class, 'bookingIndex'], ['auth:staff']);
$router->post('/admin/grooming/booking/konfirmasi', [AdminGroomingController::class, 'bookingConfirm'], ['auth:staff']);
$router->post('/admin/grooming/booking/tolak', [AdminGroomingController::class, 'bookingReject'], ['auth:staff']);
$router->post('/admin/grooming/booking/status', [AdminGroomingController::class, 'bookingUpdateStatus'], ['auth:staff']);
$router->post('/admin/grooming/booking/batalkan-refund', [AdminGroomingController::class, 'bookingCancelRefund'], ['auth:staff']);
$router->post('/admin/grooming/transaksi/refund-selesai', [AdminGroomingController::class, 'transaksiRefundSelesai'], ['auth:staff']);
$router->get('/admin/grooming/pembayaran', [AdminGroomingController::class, 'pembayaranIndex'], ['auth:staff']);
$router->post('/admin/grooming/pembayaran/setujui', [AdminGroomingController::class, 'pembayaranSetujui'], ['auth:staff']);
$router->post('/admin/grooming/pembayaran/tolak', [AdminGroomingController::class, 'pembayaranTolak'], ['auth:staff']);
$router->get('/admin/penitipan/paket', [AdminPenitipanController::class, 'paketIndex'], ['auth:staff']);
$router->get('/admin/penitipan/paket/tambah', [AdminPenitipanController::class, 'paketCreate'], ['auth:staff']);
$router->post('/admin/penitipan/paket/tambah', [AdminPenitipanController::class, 'paketStore'], ['auth:staff']);
$router->get('/admin/penitipan/paket/edit', [AdminPenitipanController::class, 'paketEdit'], ['auth:staff']);
$router->post('/admin/penitipan/paket/edit', [AdminPenitipanController::class, 'paketUpdate'], ['auth:staff']);
$router->post('/admin/penitipan/paket/hapus', [AdminPenitipanController::class, 'paketDestroy'], ['auth:staff']);
$router->get('/admin/penitipan/kamar', [AdminPenitipanController::class, 'kamarIndex'], ['auth:staff']);
$router->get('/admin/penitipan/kamar/tambah', [AdminPenitipanController::class, 'kamarCreate'], ['auth:staff']);
$router->post('/admin/penitipan/kamar/tambah', [AdminPenitipanController::class, 'kamarStore'], ['auth:staff']);
$router->get('/admin/penitipan/kamar/edit', [AdminPenitipanController::class, 'kamarEdit'], ['auth:staff']);
$router->post('/admin/penitipan/kamar/edit', [AdminPenitipanController::class, 'kamarUpdate'], ['auth:staff']);
$router->post('/admin/penitipan/kamar/hapus', [AdminPenitipanController::class, 'kamarDestroy'], ['auth:staff']);
$router->get('/admin/penitipan/kuota', [AdminPenitipanController::class, 'kuotaIndex'], ['auth:staff']);
$router->get('/admin/penitipan/kuota/tambah', [AdminPenitipanController::class, 'kuotaCreate'], ['auth:staff']);
$router->post('/admin/penitipan/kuota/tambah', [AdminPenitipanController::class, 'kuotaStore'], ['auth:staff']);
$router->get('/admin/penitipan/kuota/edit', [AdminPenitipanController::class, 'kuotaEdit'], ['auth:staff']);
$router->post('/admin/penitipan/kuota/edit', [AdminPenitipanController::class, 'kuotaUpdate'], ['auth:staff']);
$router->post('/admin/penitipan/kuota/hapus', [AdminPenitipanController::class, 'kuotaDestroy'], ['auth:staff']);
$router->get('/admin/penitipan/booking', [AdminPenitipanController::class, 'bookingIndex'], ['auth:staff']);
$router->post('/admin/penitipan/booking/konfirmasi', [AdminPenitipanController::class, 'bookingConfirm'], ['auth:staff']);
$router->post('/admin/penitipan/booking/tolak', [AdminPenitipanController::class, 'bookingReject'], ['auth:staff']);
$router->post('/admin/penitipan/booking/check-in', [AdminPenitipanController::class, 'bookingCheckIn'], ['auth:staff']);
$router->post('/admin/penitipan/booking/status', [AdminPenitipanController::class, 'bookingUpdateStatus'], ['auth:staff']);
$router->post('/admin/penitipan/booking/batalkan-refund', [AdminPenitipanController::class, 'bookingCancelRefund'], ['auth:staff']);
$router->post('/admin/penitipan/transaksi/refund-selesai', [AdminPenitipanController::class, 'transaksiRefundSelesai'], ['auth:staff']);
$router->get('/admin/penitipan/monitoring/tambah', [AdminPenitipanController::class, 'monitoringCreate'], ['auth:staff']);
$router->post('/admin/penitipan/monitoring/tambah', [AdminPenitipanController::class, 'monitoringStore'], ['auth:staff']);
$router->get('/admin/penitipan/perpanjangan', [AdminPenitipanController::class, 'perpanjanganIndex'], ['auth:staff']);
$router->post('/admin/penitipan/perpanjangan/konfirmasi', [AdminPenitipanController::class, 'perpanjanganConfirm'], ['auth:staff']);
$router->post('/admin/penitipan/perpanjangan/tolak', [AdminPenitipanController::class, 'perpanjanganReject'], ['auth:staff']);
$router->get('/admin/penitipan/pembayaran', [AdminPenitipanController::class, 'pembayaranIndex'], ['auth:staff']);
$router->post('/admin/penitipan/pembayaran/setujui', [AdminPenitipanController::class, 'pembayaranSetujui'], ['auth:staff']);
$router->post('/admin/penitipan/pembayaran/tolak', [AdminPenitipanController::class, 'pembayaranTolak'], ['auth:staff']);
